name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update theme
      run: git submodule update --init --recursive
    
    - name: Add tracking
      run: echo '<img referrerpolicy="no-referrer-when-downgrade" src="https://matomo.ozeliurs.com/matomo.php?idsite=2&amp;rec=1" style="border:0" alt="" />' >> themes/hugo-theme-stack/layouts/partials/footer/custom.html

    - name: Setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    
    - name: Build
      run: hugo -d blog

    - name: Delete contents of server folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: sudo rm -rf /root/docker-compose/www-blog/www/*

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "blog/*"
        target: "/tmp"

    - name: Permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: sudo rsync -r --delete /tmp/blog /root/docker-compose/www-blog/www && sudo chmod -R 777 /root/docker-compose/www-blog/www
        
