name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update theme
      run: git submodule update --init --recursive

    - name: Setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.91.2'
    
    - name: Build
      run: hugo -d blog

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
        source: "blog/*"
        target: "/var/www"
        
